Vagrant.configure("2") do |config|
  
  config.vm.box = "ubuntu/bionic64" 
  config.vm.network "private_network", ip: "192.168.23.10"
  config.vm.synced_folder "./", "/vagrant", owner: 1002, group: 1002
  config.disksize.size = '60GB'
  config.vm.hostname = 'game-server';
	
  cache_dir = local_cache(config.vm.box)
  config.vm.synced_folder cache_dir, "/var/cache/apt/archives/"

	config.vm.provider "virtualbox" do |vb|
		vb.name = "PokerGameServer"
		vb.memory = "4096"
		vb.cpus = "4"
	end
 
  config.vm.provision "file", source: "./install_files", destination: "/tmp/install_files"  
  config.vm.provision "shell", path: "install.sh" 
end

def local_cache(box_name)		
  cache_dir = File.join(File.expand_path(ENV["USERPROFILE"] + '\.vagrant.d'),'cache','apt',box_name)
  partial_dir = File.join(cache_dir, 'partial')
  FileUtils.mkdir_p(partial_dir) unless File.exists? partial_dir
  cache_dir
end